---
- name: install termux packages
  import_tasks: packages.yml
  tags:
    - termux_packages
    - termux_core_all

- name: configure termux environment
  import_tasks: configure.yml
  tags:
    - termux_configure
    - termux_core_all

- name: setup fixrouting
  import_tasks: fixrouting.yml
  when: termux_fixrouting |bool
  tags:
    - termux_fixrouting
    - termux_core_all

- name: setup termux services
  import_tasks: services.yml
  tags:
    - termux_services
    - termux_core_all

- name: setup ubuntu image in termux proot
  import_tasks: proot.yml
  when: termux_ubuntu |d('')
  tags:
    - termux_proot
    - termux_ubuntu_bootstrap
    - termux_core_all
  vars:
    ubuntu_fs: "{{ termux_ubuntu_fs }}"
    start_script: "{{ termux_ubuntu_start_script }}"
    codename: "{{ termux_ubuntu |d('bionic') }}"
    image_host: "{{ termux_ubuntu_image_host }}"
    tarball: "{{ termux_ubuntu_dir }}/image.tgz"

- name: bootstrap ubuntu in termux
  import_tasks: ubuntu-bootstrap.yml
  when: termux_ubuntu |d('')
  tags:
    - termux_ubuntu_bootstrap
    - termux_ubuntu
    - termux_core_all
  vars:
    ubuntu_fs: "{{ termux_ubuntu_fs }}"
    start_script: "{{ termux_ubuntu_start_script }}"
    core_packages_args: "{{ termux_ubuntu_core_packages |join(' ') }}"

- name: run postponed handlers now
  meta: flush_handlers
  tags: always
...
