---
- name: install termux packages
  import_tasks: packages.yml
  tags:
    - termux_packages
    - termux_core_all

- name: configure termux environment
  import_tasks: configure.yml
  tags:
    - termux_configure
    - termux_core_all

- name: setup proot and bootstrap ubuntu in termux
  import_tasks: proot.yml
  when: proot_ubuntu |default('')
  tags:
    - termux_proot
    - termux_ubuntu
    - termux_core_all
  vars:
    ubuntu_dir: "{{ termux_ubuntu_dir }}"
    ubuntu_fs: "{{ termux_ubuntu_fs }}"
    codename: "{{ termux_ubuntu_codename }}"
    image_host: "{{ termux_ubuntu_image_host }}"
    tarball: "{{ termux_ubuntu_tarball }}"
    start_script: "{{ termux_ubuntu_start_script }}"
    core_packages_args: "{{ termux_ubuntu_core_packages |join(' ') }}"

- name: run postponed handlers now
  meta: flush_handlers
  tags: always
...
