---
- name: install utilities
  command:
    cmd: "pkg install {{ termux_packages_core |join(' ') }}"
    stdin: "{{ termux_pkg_confirm }}"
  environment:
    DEBIAN_FRONTEND: noninteractive
  register: pkg_result
  changed_when: pkg_result.stdout |default('') is search(termux_pkg_changed)

- name: prevent sleep
  command: termux-wake-lock
  changed_when: false
  when: ansible_connection != 'docker'

- name: add x11 repository
  command:
    cmd: "pkg install x11-repo"
    stdin: "{{ termux_pkg_confirm }}"
  environment:
    DEBIAN_FRONTEND: noninteractive
  register: pkg_result
  changed_when: pkg_result.stdout |default('') is search(termux_pkg_changed)
  when: termux_x11 |bool

- name: install x11 programs
  command:
    cmd: "pkg install {{ termux_packages_x11 |join(' ') }}"
    stdin: "{{ termux_pkg_confirm }}"
  environment:
    DEBIAN_FRONTEND: noninteractive
  register: pkg_result
  changed_when: pkg_result.stdout |default('') is search(termux_pkg_changed)
  when: termux_x11 |bool

- name: upgrade packages
  command:
    cmd: pkg upgrade
    stdin: "{{ termux_pkg_confirm }}"
  environment:
    DEBIAN_FRONTEND: noninteractive
  register: pkg_result
  changed_when: pkg_result.stdout |default('') is search(termux_pkg_changed)
  ignore_errors: true
...
