---
- name: install termux utilities
  command: "pkg install -qy {{ termux_packages_core |join(' ') }}"
  environment:
    DEBIAN_FRONTEND: noninteractive
  register: pkg_result
  changed_when: pkg_result.stdout |default('') is search(termux_pkg_changed)

- name: prevent termux from sleep during setup
  command: termux-wake-lock
  changed_when: false
  when: ansible_connection != 'docker'

- name: add x11 repository
  command: "pkg install -qy x11-repo"
  environment:
    DEBIAN_FRONTEND: noninteractive
  register: pkg_result
  changed_when: pkg_result.stdout |default('') is search(termux_pkg_changed)
  when: termux_x11 |bool

- name: install x11 programs
  command: "pkg install -qy {{ termux_packages_x11 |join(' ') }}"
  environment:
    DEBIAN_FRONTEND: noninteractive
  register: pkg_result
  changed_when: pkg_result.stdout |default('') is search(termux_pkg_changed)
  when: termux_x11 |bool

- name: upgrade termux packages
  command:
    cmd: pkg upgrade
    stdin: "{{ termux_pkg_confirm }}"
  environment:
    DEBIAN_FRONTEND: noninteractive
  register: pkg_result
  changed_when: pkg_result.stdout |default('') is search(termux_pkg_changed)
  ignore_errors: true
  when: termux_upgrade |bool
...
