---
- name: install termux utilities
  command: "pkg install {{ termux_pkg_opts }} {{ termux_packages_core |join(' ') }}"
  environment: "{{ termux_pkg_env }}"
  register: pkg_result
  until: pkg_result is successful
  changed_when: pkg_result.stdout |d('') is search(termux_pkg_changed)

- name: prevent termux from sleep during setup
  command: termux-wake-lock
  changed_when: false
  when: ansible_connection != 'docker'

- name: add x11 repository
  command: "pkg install {{ termux_pkg_opts }} x11-repo"
  environment: "{{ termux_pkg_env }}"
  register: pkg_result
  until: pkg_result is successful
  changed_when: pkg_result.stdout |d('') is search(termux_pkg_changed)
  when:
    - termux_x11 |bool
    - not termux_mini |bool

- name: install x11 programs
  command: "pkg install {{ termux_pkg_opts }} {{ termux_packages_x11 |join(' ') }}"
  environment: "{{ termux_pkg_env }}"
  register: pkg_result
  until: pkg_result is successful
  changed_when: pkg_result.stdout |d('') is search(termux_pkg_changed)
  when:
    - termux_x11 |bool
    - not termux_mini |bool

- name: upgrade termux packages
  command:
    cmd: "pkg upgrade {{ termux_pkg_opts }}"
    stdin: "{{ termux_pkg_confirm }}"
  environment: "{{ termux_pkg_env }}"
  register: pkg_result
  until: pkg_result is successful
  changed_when: pkg_result.stdout |d('') is search(termux_pkg_changed)
  ignore_errors: true
  when:
    - termux_upgrade |bool
    - not termux_mini |bool
...
